name: CustomCraftingRecipesPlugin
version: '1.0-SNAPSHOT'
main: me.fofola1.customCraftingRecipesPlugin.CustomCraftingRecipesPlugin
api-version: '1.20'
authors: [ FOFOLA_1 ]

commands:
  customrecipe:
    description: main menu of custom crafting recipe plugin
    usage: /<command>
    permission: customrecipes.menu
    aliases:
      - cr
      - crecipe


  getlangstring:
    description: test

  getnewenfile:
    description: test

  getmenudata:
    description: test

  getitemslist:
    description: test

  getrecipeitems:
    description: test

  getrecipe:
    description: test

  removerecipe:
    description: test

permissions:
  permissions.menu:
    description: allows to edit custom recipes and use menu of the plugin
    default: op