name: Builder
run-name: ${{ github.actor }} has started build
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - run: wget "https://dlcdn.apache.org/maven/maven-4/4.0.0-rc-2/binaries/apache-maven-4.0.0-rc-2-bin.tar.gz"
    - run: tar -zxf apache-maven-4.0.0-rc-2-bin.tar.gz

    
    - run: |
        pwd
        ls
        mvn clean
      working-directory: ${{ github.workspace }}
    - run: |
        pwd
        mvn compile
    - run: mvn package