name: Builder
run-name: ${{ github.actor }} has started build
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Maven
      uses: hb0730/maven-action@v1.0.2
      with:
        maven-version: 4.0.0
        maven-file: ${{ runner.temp }}/apache-maven-4.0.0-bin.tar.gz
        url: https://dlcdn.apache.org/maven/maven-4/4.0.0-rc-2/binaries/apache-maven-4.0.0-rc-2-bin.tar.gz

    - run: mvn clean
    - run: mvn compile
    - run: mvn package